import React from "react";
import Head from "next/head";
import { BiPlus } from "react-icons/bi";
import Table from "../components/table";
import Form from "../components/form";
import SearchInput from "../components/SearchInput";
import { useState, useEffect } from "react";
import fetcher from "../lib/utils/fetcher";
import Success from "@/components/success";

export default function Home() {
  const addHandler = () => {
    setVisible(!visible);
  };
  const handleDiscussionAdded = () => {
    setVisible(!visible);
    setSuccess(!success);
  };

  // const [discussion, setDiscussion] = useState(null);
  const [empty, setEmpty] = useState(false);
  let arr;
  const [visible, setVisible] = useState(false);
  const [success, setSuccess] = useState(false);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const response = await fetch("https://deploy-project-389113.et.r.appspot.com/discussion");
        const discussions = await response.json();
        console.log(discussions.data.discussions);
        arr = discussions.data.discussions;
        // setDiscussion(discussions.data.discussions);
      } catch (error) {
        console.error("Error fetching data:", error);
      }
    };
    fetchData();
  }, []);

  return (
    <>
      <Head>
        <title>CRUD App</title>
        <meta name="description" content="Generated by C23-DF01" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="py-5">
        <h1 className="text-xl md:text-5xl text-center font-bold py-10">
          CRUD App Discussion Forum
        </h1>

        <div className="container mx-auto flex justify-between py-5">
          <div className="left flex gap-3">
            <button
              onClick={addHandler}
              className="flex bg-indigo-500 text-white px-5 py-2 border rounded-md hover:bg-gray-50 hover:border-indigo-500 hover:text-gray-400"
            >
              Add Discussion
              <span className="px-1">
                <BiPlus size={23} />
              </span>
            </button>
          </div>
          <SearchInput />
        </div>

        {/* Form */}
        {visible ? (
          <Form onDiscussionAdded={handleDiscussionAdded}></Form>
        ) : (
          <></>
        )}
        {success ? (
          <Success message={"Data succesfully been added"}></Success>
        ) : (
          <></>
        )}
        {/* Table */}
        <div className="container mx-auto">
          {arr && Object.keys(arr).length > 0 ? (
            <Table empty={empty} discussion={arr} />
          ) : (
            <p>No discussion found.</p>
          )}
        </div>
      </main>
    </>
  );
}
