import React from 'react';
import Head from 'next/head';
import { BiPlus } from 'react-icons/bi';
import Table from '../components/table';
import Form from '../components/form';

export default function Home() {
  return (
    <>
      <Head>
        <title>CRUD App</title>
        <meta name="description" content="Generated by C23-DF01" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="py-5">
        <h1 className="text-xl md:text-5xl text-center font-bold py-10">CRUD App Discussion Forum</h1>

        <div className="container mx-auto flex justify-between py-5 border-b">
          <div className="left flex gap-3">
            <button className="flex bg-indigo-500 text-white px-4 py-2 border rounded-md hover:bg-gray-200 hover:border-indigo-500 hover:text-gray-800">
              Add Discussion
              <span className="px-1"><BiPlus size={23} /></span>
            </button>
          </div>
        </div>

        {/* Form */}
        <div className="container mx-auto py-5">
          <Form />
        </div>

        {/* Table */}
        <div className="container mx-auto">
          <Table />
        </div>
      </main>
    </>
  );
}
